default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipes_app_4x8y

test:
  <<: *default
  database: recipes_app_4x8y

production:
  <<: *default
  database: recipes_app_4x8y
  username: recipes_app_4x8y_user
  password: <%= ENV["RECIPES_DATABASE_PASSWORD"] %>
