default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  schema_search_path: "recipes_schema,public"

development:
  <<: *default
  database: shared_database_name

test:
  <<: *default
  database: shared_database_name

production:
  <<: *default
  database: shared_database_name
  username: recipes
  password: <%= ENV["RECIPES_DATABASE_PASSWORD"] %>
  url:  <%= ENV['DATABASE_URL'] %>
